$('input').css('border', '1px solid red');//
//$('input:button').css('border', '1px solid red');//
//$('input:radio').css('border', '1px solid red');//
//$('input:checkbox').css('border', '1px solid red');//
//$('input:text').css('border', '1px solid red');//
//$('input:password').css('border', '1px solid red');//
//$('input:file').css('border', '1px solid red');//
//$('input:submit').css('border', '1px solid red');//
//$('input:reset').css('border', '1px solid red');//
//$('input:image').css('border', '1px solid red');//
//$('input:focus').css('border', '1px solid red');//
//$('input:checked').css('border', '1px solid red');//
//$('input:enabled').css('border', '1px solid red');//
//$('input:disabled').css('border', '1px solid red');//